import { useState, useEffect, useContext } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { io } from "socket.io-client";
// import Image from "next/image";
// import styles from "../styles/Home.module.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faSpinner } from "@fortawesome/free-solid-svg-icons";
import { useRouter } from "next/router";
import { SocketContext } from "../contexts/SocketContext";

const Home: NextPage = () => {
  const [choice, setChoice] = useState("");
  const [isConnected, setIsConnected] = useState<boolean>(false);
  const [isConnectedToRoom, setIsConnectedToRoom] = useState<boolean>(false);
  const [roomCode, setRoomCode] = useState<string>("");
  const [socket, setSocket] = useState<any>(null);
  const [username, setUsername] = useState<string>("");
  const router = useRouter();
  const socketContext = useContext(SocketContext);

  useEffect(() => {
    let newSocket = io("ws://localhost:5000");

    if (socketContext.socket == null) {
      socketContext.setSocket(newSocket);
      setIsConnected(true);
    } else {
      setIsConnected(true);
    }

    // newSocket.on("connect", () => {
    //   setIsConnected(true);
    // });
  }, [socketContext]);

  return (
    <div className="bg-white min-h-screen flex flex-col justify-center align-middle gap-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <div className="text-black text-6xl text-center">msg-it</div>
      {isConnected ? (
        <div className="flex flex-col justify-center items-center">
          Socket Context id is{" "}
          {socketContext ? socketContext?.socket.id : "Loading..."}
          <div className="mb-4 font-semibold">What should we call you?</div>
          <div className="flex gap-2">
            <input
              className="p-2 text-center border-2 rounded-full border-button-bg"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
            ></input>
            <button
              className="bg-button-bg text-white text-lg p-2 px-4 rounded-full"
              onClick={(e) => {
                socketContext.setUsername(username);
                router.push("/room/testRoom");
              }}
            >
              Go!
            </button>
          </div>
        </div>
      ) : (
        <FontAwesomeIcon
          icon={faSpinner}
          className="animate-spin w-8 self-center fill-blue-400"
          color="#6277f2"
        />
      )}
    </div>
  );
};

export default Home;
