import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="bg-white min-h-screen flex flex-col justify-center align-middle gap-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <div className="text-black text-6xl text-center">msg-it</div>
      <div className="flex justify-center gap-4">
        <button className="bg-button-bg text-white text-lg p-2 px-4 rounded-full">
          Create a Room
        </button>

        <button className="bg-button-bg text-white text-lg p-2 px-4 rounded-full">
          Join a Room
        </button>
      </div>
    </div>
  );
};

export default Home;
